---
version: '2'
services:
  kafka:
    image: landoop/kafka-lenses-dev
    network_mode: host
    ports:
      - "3030:3030"
      - "9092:9092"
      - "2181:2181"
      - "8081:8081"
      - "9581:9581"
      - "9582:9582"
      - "9584:9584"
      - "9585:9585"
    environment:
      EULA: "https://dl.lenses.stream/d/?id=bd421b96-1882-4216-bc2e-cecd182d1b16"
      ADV_HOST: "127.0.0.1"
